comments, curl file check

diff --git a/.github/workflows/arduino.yml b/.github/workflows/arduino.yml
--- a/.github/workflows/arduino.yml
+++ b/.github/workflows/arduino.yml
@@ -179,10 +179,17 @@ jobs:
           popd # GITHUB_WORK
 
 
+          # ** END ** Get wolfssl-examples
 
       - name: Install wolfSSL Arduino library
         run: |
-          echo "Run the local wolfssl-arduino.sh install script to install wolfssl Arduino library."
+          # Run the local wolfssl-arduino.sh install script to install wolfssl Arduino library.
+
+          # Methods of installing Arduino library:
+          #   1) arduino-cli lib install "wolfSSL"
+          #   2) manual copy of files (typical of the Arduino-wolfssl repo)
+          #   3) run ./wolfssl-arduino.sh INSTALL (typical of the wolfssl repo)
+
           echo "Current pwd for wolfssl-examples clone fetch: $(pwd)"
           GITHUB_WORK=$(realpath "$GITHUB_WORKSPACE/../..")
           echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
@@ -192,16 +199,17 @@ jobs:
           pwd
           pushd ./IDE/ARDUINO
 
-            # Set default ARDUINO_ROOT. TODO: once script is updated, this should be removed.
+            # Set default ARDUINO_ROOT to Arduino library.
             export ARDUINO_ROOT="$HOME/Arduino/libraries"
             export WOLFSSL_EXAMPLES_ROOT="$GITHUB_WORK/wolfssl-examples-publish"
 
-            echo "ARDUINO_ROOT=$WOLFSSL_EXAMPLES_ROOT"
-            echo "WOLFSSL_EXAMPLES_ROOT=$WOLFSSL_EXAMPLES_ROOT"
+            echo "ARDUINO_ROOT:          $WOLFSSL_EXAMPLES_ROOT"
+            echo "WOLFSSL_EXAMPLES_ROOT: $WOLFSSL_EXAMPLES_ROOT"
 
             bash ./wolfssl-arduino.sh INSTALL  # Install wolfSSL library
           popd
 
+          # ** END ** Install wolfSSL Arduino library
 
       - name: List installed Arduino libraries
         run: arduino-cli lib list
@@ -218,8 +226,39 @@ jobs:
 
           # Fetch script and board list into WOLFSSL_EXAMPLES_DIRECTORY
           # TODO edit PR branch path:
-          curl -L https://raw.githubusercontent.com/$REPO_OWNER/wolfssl-examples/examples_dev/Arduino/sketches/board_list.txt          -o "$WOLFSSL_EXAMPLES_DIRECTORY/board_list.txt"
-          curl -L https://raw.githubusercontent.com/$REPO_OWNER/wolfssl-examples/examples_dev/Arduino/sketches/compile-all-examples.sh -o "$WOLFSSL_EXAMPLES_DIRECTORY/compile-all-examples.sh"
+          curl -L "https://raw.githubusercontent.com/$REPO_OWNER/wolfssl-examples/examples_dev/Arduino/sketches/board_list.txt"          -o "$WOLFSSL_EXAMPLES_DIRECTORY/board_list.txt"
+
+          # Check if the first line is "404: Not Found" - which would indicate the curl path above is bad.
+          FILE="$WOLFSSL_EXAMPLES_DIRECTORY/board_list.txt"
+
+          # Ensure the file exists
+          if [[ ! -f "$FILE" ]]; then
+              echo "File not found: $FILE"
+              exit 1
+          fi
+
+          # Check if the first line is "404: Not Found"
+          if [[ $(head -n 1 "$FILE") == "404: Not Found" ]]; then
+              echo "The first line is '404: Not Found'"
+              exit 1
+          fi
+
+          curl -L "https://raw.githubusercontent.com/$REPO_OWNER/wolfssl-examples/examples_dev/Arduino/sketches/compile-all-examples.sh" -o "$WOLFSSL_EXAMPLES_DIRECTORY/compile-all-examples.sh"
+
+          # Check if the first line is "404: Not Found" - which would indicate the curl path above is bad.
+          FILE="$WOLFSSL_EXAMPLES_DIRECTORY/compile-all-examples.sh"
+
+          # Ensure the file exists
+          if [[ ! -f "$FILE" ]]; then
+              echo "File not found: $FILE"
+              exit 1
+          fi
+
+          # Check if the first line is "404: Not Found"
+          if [[ $(head -n 1 "$FILE") == "404: Not Found" ]]; then
+              echo "The first line is '404: Not Found'"
+              exit 1
+          fi
 
           pushd "$WOLFSSL_EXAMPLES_DIRECTORY"
             echo "Current directory:           $PWD"
@@ -234,7 +273,7 @@ jobs:
             echo "Found compile script: $(ls -al ./compile-all-examples.sh)"
           popd
 
-          # End Get compile-all-examples.sh
+          # ** END ** Get compile-all-examples.sh
 
       # This will fail with Arduino published wolfSSL v5.7.6 and older
       # as the examples moved. See https://github.com/wolfSSL/wolfssl/pull/8514
