only check for CRLF in non-binary encoding

diff --git a/.github/workflows/my_visual-studio.yml b/.github/workflows/my_visual-studio.yml
--- a/.github/workflows/my_visual-studio.yml
+++ b/.github/workflows/my_visual-studio.yml
@@ -41,16 +41,19 @@ jobs:
           echo "Checking line endings..."
           for file in $(git ls-files '*.vcxproj' '*.csproj' '*.sln'); do
             if grep -IL . "$file"; then
+              # check for binary encoding, including UTF-* with BOM
               # echo "❌ ERROR: $file contains non-text content"
               echo -e "\033[33m⚠️ WARNING:  $file contains non-text content!\033[0m"
               errors=$((errors + 1))
-            fi
-            if ! grep -qP '\r\n' "$file"; then
-              # echo "❌ERROR: $file does not have CRLF line endings"
-              echo -e "\033[33m⚠️ WARNING: $file does not have CRLF line endings!\033[0m"
-              errors=$((errors + 1))
             else
-              echo "✅ $file has correct CRLF line endings"
+                # grep -P will fail for UTF-8 with BOM, so only check CRLF here:
+                if ! grep -qP '\r\n' "$file"; then
+                  # echo "❌ERROR: $file does not have CRLF line endings"
+                  echo -e "\033[33m⚠️ WARNING: $file does not have CRLF line endings!\033[0m"
+                  errors=$((errors + 1))
+                else
+                  echo "✅ $file has correct CRLF line endings"
+                fi
             fi
           done
 
